export const patientList = [
    {
        id: 1,
        patientName:'Sara Smith', 
        admissionDate:'15-Aug-2021', 
        status: true, 
        image:'assets/media/user1.png',
        phone: '304-323-23s4',
        email: 'sara@email.com',
        gender: 'female',
        age: 45,
        surgeryType: 'Roaster Cuff Repair',
        surgeryDate: '15 Aug 2021',
        lastUpdated: '15 aug 2021',
        height: 163,
        weight: 110,
        BMI: 19,
        anesthesiologist: 'Dr.Christina Hardway',
        anesthesiologistPhone: '238-342-1234',
        anesthesiologistEmail: 'christina@email.com',
        sugeryClearance: true
    },

    {
        id: 2,
        patientName:'James Johnson', 
        admissionDate:'15-Aug-2020', 
        status: false, 
        image:'assets/media/user4.png',
        phone: '304-323-23s4',
        email: 'james@email.com',
        gender: 'Male',
        age: 45,
        surgeryType: 'Cuff Repair',
        surgeryDate: '25 Aug 2021',
        lastUpdated: '15 aug 2021',
        height: 163,
        weight: 110,
        BMI: 19,
        anesthesiologist: 'Dr.Christina Hardway',
        anesthesiologistPhone: '238-342-1234',
        anesthesiologistEmail: 'christina@email.com',
        sugeryClearance: true,
    },
      
    {
        id: 3,
        patientName:'Partice Page', 
        admissionDate:'20-Aug-2020', 
        status: true, 
        image:'assets/media/user3.png',
        phone: '304-323-2456',
        email: 'page@email.com',
        gender: 'female',
        age: 35,
        surgeryType: 'Bipolar Surgery',
        surgeryDate: '10 may 2021',
        lastUpdated: '15 aug 2021',
        height: 159,
        weight: 70,
        BMI: 17,
        anesthesiologist: 'Dr.Christina Hardway',
        anesthesiologistPhone: '238-342-1234',
        anesthesiologistEmail: 'christina@email.com',
        sugeryClearance: false,
    },
    {
        id: 4,
        patientName:'Rajender desai', 
        admissionDate:'21-Aug-2020', 
        status: true, 
        image:'assets/media/user2.png',
        phone: '304-323-2354',
        email: 'rajender@email.com',
        gender: 'Male',
        age: 35,
        surgeryType: 'Bipolar Surgery',
        surgeryDate: '10 may 2021',
        lastUpdated: '15 aug 2021',
        height: 159,
        weight: 70,
        BMI: 17,
        anesthesiologist: 'Dr.Christina Hardway',
        anesthesiologistPhone: '238-342-1234',
        anesthesiologistEmail: 'christina@email.com',
        sugeryClearance: false,
    }
]